version: "3"

services:
  watchtower:
    hostname: watchtower
    container_name: watchtower
    image: v2tec/watchtower
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik
    networks:
      - web
      - internal
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/etc/traefik/traefik.toml
      - ./config/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.domain=${DOMAIN_NAME}"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_TRAEFIK}.${DOMAIN_NAME}"
      - "traefik.port=8080"
    restart: always

  plex:
    hostname: plex
    container_name: plex
    image: plexinc/pms-docker
    networks:
      - web
    environment:
      - PLEX_CLAIM=${PLEX_TOKEN}
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - ./plex/config:/config \
      - ./plex/transcode:/transcode \
      - ./plex/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PLEX}.${DOMAIN_NAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"

  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    networks:
      - web
    ports:
      - "3000:3000"
    volumes: 
      - ./grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_GRAFANA}.${DOMAIN_NAME}"
      - "traefik.port=3000"
    restart: always

networks:
  internal:
    driver: bridge
  web:
    external: true
