version: "3"

services:
  plex:
    hostname: plex
    container_name: plex
    image: plexinc/pms-docker
    networks:
      - web
    environment:
      - PLEX_CLAIM=${PLEX_TOKEN}
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - $PWD/plex/config:/config \
      - $PWD/plex/transcode:/transcode \
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PLEX}.${DOMAIN_NAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
    restart: always


networks:
  web:
    external: true
