version: "3"

services:
  plex:
    hostname: plex
    container_name: plex
    image: plexinc/pms-docker
    networks:
      - internal
      - web
    environment:
      - PLEX_CLAIM=${PLEX_TOKEN}
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - TZ=${TZ}
      - ADVERTISE_IP=https://${SUBDOMAIN_PLEX}.${DOMAIN_NAME}:443
    volumes:
      - /mnt/configs/plex/config:/config
      - /mnt/configs/plex/transcode:/transcode
      - ${PLEX_MOVIES1}:/data/movies1
      - ${PLEX_MOVIES2}:/data/movies2
      - ${PLEX_MOVIES3}:/data/movies3
      - ${PLEX_MOVIES4}:/data/movies4
      - ${PLEX_MOVIES5}:/data/movies5
      - ${PLEX_TVSHOWS1}:/data/tvshows1
      - ${PLEX_TVSHOWS2}:/data/tvshows2
      - ${PLEX_ANIME1}:/data/anime
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.rule=Host(`${SUBDOMAIN_PLEX}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plex.middlewares=plex-https-redirect"
      - "traefik.http.routers.plex-secure.entrypoints=web-secure"
      - "traefik.http.routers.plex-secure.rule=Host(`${SUBDOMAIN_PLEX}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.tls.certresolver=default"
      - "traefik.http.routers.plex-secure.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.docker.network=web"
    restart: always

  ombi:
    hostname: ombi
    container_name: ombi
    image: linuxserver/ombi
    networks:
      - internal
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/ombi/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ombi.entrypoints=web"
      - "traefik.http.routers.ombi.rule=Host(`${SUBDOMAIN_OMBI}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.ombi-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ombi.middlewares=ombi-https-redirect"
      - "traefik.http.routers.ombi-secure.entrypoints=web-secure"
      - "traefik.http.routers.ombi-secure.rule=Host(`${SUBDOMAIN_OMBI}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.ombi-secure.tls=true"
      - "traefik.http.routers.ombi-secure.tls.certresolver=default"
      - "traefik.http.routers.ombi-secure.service=ombi"
      - "traefik.http.services.ombi.loadbalancer.server.port=3579"
      - "traefik.docker.network=web"
    depends_on:
      - plex
    restart: always

  tautulli:
    hostname: tautulli
    container_name: tautulli
    image: tautulli/tautulli
    networks:
      - internal
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/tautulli/config:/config
      - /mnt/configs/plex/config/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=web"
      - "traefik.http.routers.tautulli.rule=Host(`${SUBDOMAIN_TAUTULLI}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.tautulli-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tautulli.middlewares=tautulli-https-redirect"
      - "traefik.http.routers.tautulli-secure.entrypoints=web-secure"
      - "traefik.http.routers.tautulli-secure.rule=Host(`${SUBDOMAIN_TAUTULLI}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.tautulli-secure.tls=true"
      - "traefik.http.routers.tautulli-secure.tls.certresolver=default"
      - "traefik.http.routers.tautulli-secure.service=tautulli"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.docker.network=web"
    depends_on:
      - plex
    restart: always

networks:
  internal:
    driver: bridge
  web:
    external: true
