version: "3"

services:
  plex:
    hostname: plex
    container_name: plex
    image: plexinc/pms-docker
    networks:
      - web
    environment:
      - PLEX_CLAIM=${PLEX_TOKEN}
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - TZ=${TZ}
      - ADVERTISE_IP=https://${SUBDOMAIN_PLEX}.${DOMAIN_NAME}:443
    volumes:
      - /mnt/configs/plex/config:/config
      - /mnt/configs/plex/transcode:/transcode
      - ${PLEX_MOVIES1}:/data/movies1
      - ${PLEX_MOVIES2}:/data/movies2
      - ${PLEX_MOVIES3}:/data/movies3
      - ${PLEX_MOVIES4}:/data/movies4
      - ${PLEX_MOVIES5}:/data/movies5
      - ${PLEX_TVSHOWS1}:/data/tvshows1
      - ${PLEX_TVSHOWS2}:/data/tvshows2
      - ${PLEX_ANIME1}:/data/anime
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PLEX}.${DOMAIN_NAME}"
      - "traefik.port=32400"
    restart: always

  ombi:
    hostname: ombi
    container_name: ombi
    image: linuxserver/ombi
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/ombi/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_OMBI}.${DOMAIN_NAME}"
      - "traefik.port=3579"
    depends_on:
      - plex
    restart: always

  tautulli:
    hostname: tautulli
    container_name: tautulli
    image: tautulli/tautulli
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - /mnt/configs/tautulli/config:/config
      - /mnt/configs/plex/config/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=tautulli"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_TAUTULLI}.${DOMAIN_NAME}"
      - 'traefik.port=8181'
    depends_on:
      - plex
    restart: always

networks:
  web:
    external: true
