version: "3.7"

services:
  prometheus:
    hostname: prometheus
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.routers.prometheus.rule=Host(`${SUBDOMAIN_PROMETHEUS}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=web-secure"
      - "traefik.http.routers.prometheus-secure.rule=Host(`${SUBDOMAIN_PROMETHEUS}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prometheus-secure.middlewares=prometheus-auth"
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.tls.certresolver=default"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=web"
    volumes:
      - $PWD/cache/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  cadvisor:
    hostname: cadvisor
    container_name: cadvisor
    image: google/cadvisor:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.entrypoints=web"
      - "traefik.http.routers.cadvisor.rule=Host(`${SUBDOMAIN_CADVISOR}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.cadvisor-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.cadvisor.middlewares=cadvisor-https-redirect"
      - "traefik.http.routers.cadvisor-secure.entrypoints=web-secure"
      - "traefik.http.routers.cadvisor-secure.rule=Host(`${SUBDOMAIN_CADVISOR}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.cadvisor-secure.middlewares=cadvisor-auth"
      - "traefik.http.middlewares.cadvisor-auth.basicauth.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.http.routers.cadvisor-secure.tls=true"
      - "traefik.http.routers.cadvisor-secure.tls.certresolver=default"
      - "traefik.http.routers.cadvisor-secure.service=cadvisor"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      - "traefik.docker.network=web"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: always

networks:
  internal:
    driver: bridge
  web:
    external: true
