version: "3.7"

services:
  watchtower:
    hostname: watchtower
    container_name: watchtower
    image: v2tec/watchtower
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik:latest
    networks:
      - web
      - internal
    ports:
      - "80:80"     
      - "443:443"   
      - "8080:8080"
    environment:
      - DUCKDNS_TOKEN=${TOKEN}
      - TZ=${TZ}
    command: 
      - "--certificatesresolvers.default.acme.email=${ACME_EMAIL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${SUBDOMAIN_TRAEFIK}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${SUBDOMAIN_TRAEFIK}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=default"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/data/traefik.yml:/traefik.yml
      - $PWD/data/acme.json:/acme.json
    restart: always

  duckdns:
    hostname: duckdns
    container_name: duckdns
    image: linuxserver/duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DOMAIN_NAME}
      - TOKEN=${TOKEN}
    restart: always

networks:
  internal:
    driver: bridge
  web:
    external: true
