version: "3"

services:
  watchtower:
    hostname: watchtower
    container_name: watchtower
    image: v2tec/watchtower
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik
    networks:
      - web
      - internal
    ports:
      - "80:80"     
      - "443:443"   
      - "8080:8080"
    environment:
      - DUCKDNS_TOKEN=${TOKEN}
    command: --acme.email="${ACME_EMAIL}" \
      --acme.dnsChallenge.provider="${DNS_PROVIDER}" \ 
      --acme.dnsChallenge.delayBeforeCheck=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme.json:/acme.json
    restart: always

  duckdns:
    hostname: duckdns
    container_name: duckdns
    image: linuxserver/duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DOMAIN_NAME}
      - TOKEN=${TOKEN}
    restart: always

networks:
  internal:
    driver: bridge
  web:
    external: true
