version: "3"

services: 
  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    networks:
      - web
    ports:
      - "3000:3000"
    volumes: 
      - ./grafana:/config
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana-volume:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_GRAFANA}.${DOMAIN_NAME}"
      - "traefik.port=3000"
    restart: always

volumes:
  grafana-volume:
    external: true

networks:
  web:
    external: true
