version: "3"

services: 
  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - internal
      - web
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,natel-discrete-panel
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - $PWD/configs/grafana.ini:/etc/grafana/grafana.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`${SUBDOMAIN_GRAFANA}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=web-secure"
      - "traefik.http.routers.grafana-secure.rule=Host(`${SUBDOMAIN_GRAFANA}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=default"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    restart: always

  renderer:
    hostname: grafana-image-renderer
    container_name: grafana-image-renderer
    image: grafana/grafana-image-renderer:latest
    networks:
     - internal
    restart: always

  loki:
    hostname: loki
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal
    restart: always

  promtail:
    hostname: promtail
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - internal
    restart: always

volumes:
  grafana-storage:

networks:
  internal:
    driver: bridge
  web:
    external: true
