version: "3"

services: 
  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - internal
      - web
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,natel-discrete-panel
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - $PWD/configs/grafana.ini:/etc/grafana/grafana.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`${SUBDOMAIN_GRAFANA}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=web-secure"
      - "traefik.http.routers.grafana-secure.rule=Host(`${SUBDOMAIN_GRAFANA}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=default"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    restart: always

volumes:
  grafana-storage:

networks:
  internal:
    driver: bridge
  web:
    external: true
