version: "3"

services:
  organizr:
    hostname: organizr
    container_name: organizr
    image: organizrtools/organizr-v2
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /mnt/configs/organizr/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.entrypoints=web"
      - "traefik.http.routers.organizr.rule=Host(`${SUBDOMAIN_ORGANIZR}.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.organizr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.organizr.middlewares=organizr-https-redirect"
      - "traefik.http.routers.organizr-secure.entrypoints=web-secure"
      - "traefik.http.routers.organizr-secure.rule=Host(`${SUBDOMAIN_ORGANIZR}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.organizr-secure.tls=true"
      - "traefik.http.routers.organizr-secure.tls.certresolver=default"
      - "traefik.http.routers.organizr-secure.service=organizr"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    restart: always

networks:
  web:
    external: true
