version: "3"

services:
  portainer:
    hostname: portainer
    container_name: portainer
    image: portainer/portainer
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/configs/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PORTAINER}.${DOMAIN_NAME}"
      - "traefik.port=9000"
    restart: always

networks:
  web:
    external: true
