version: "3.7"

services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb
    networks:
      - internal
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always

volumes:
  influxdb-storage:

networks:
  internal:
    driver: bridge
